
previews:
  generation: automatic

services:
  - type: pserv
    runtime: node
    name: revento-bot
    repo: https://github.com/azcera/reventobot
    disk:
      name: data
      mountPath: /data
      sizeGB: 1